Skeleton
js-tasks-ru/htmlcss-20230530_prasolovp-s pull request #10
Opened 2023-06-15 09:16 UTC by 25S01ve

2023-06-15 09:16 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-15 20:13 UTC, GSemikozov requested changes

2023-06-15 20:13 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.wrapper{
блок wrapper? какой-то побочный / вспомогательный? по разметке - все-таки определяющий. Так что - это ошибка. Блок у нас называется .skeleton. Все что внутри - его элементы и модификаторы

2023-06-16 01:00 UTC, 25S01ve commented on 04-lection2/02-skeleton/skeleton.css
> +.wrapper{
Это просто для ширины, чтобы не раползался скелетон на весь экран, хотя по содержимому внутри вроде бы и не должен, ок - уберу, поэкспериментирую.

2023-06-16 05:01 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-16 05:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-16 08:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-18 09:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-18 09:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-18 12:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-18 12:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-20 13:32 UTC, closed without merging