Skeleton solution
js-tasks-ru/htmlcss-20230530_prasolovp-s pull request #16
Opened 2023-06-20 13:35 UTC by 25S01ve

2023-06-20 13:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-21 09:43 UTC, GSemikozov requested changes

2023-06-21 09:43 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.wrapper{
удалим

2023-06-21 09:43 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    padding: 24px;
не совсем по дизайну)

2023-06-21 09:43 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin: 0 16px 24px 0;
картинке не нужен отступ снизу

2023-06-21 09:43 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.imgName__wrapper{
почему .imgName? блок называется .skeleton, а все его элементы в названии класса содержут префиксом .skeleton - например `.skeleton__top`

2023-06-21 09:43 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    justify-content: flex-start;
еще бы align-items: center?

2023-06-21 09:43 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.titleName__wrapper{
.skeleton__box?

2023-06-21 09:43 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 400px;
лишнее

2023-06-21 09:43 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    padding-top: 8px;
лишнее (лучше выравнивать по середине через align-items: center)

2023-06-21 09:43 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    border: 1px solid var(--grey-2);
бордер здесь не нужен

2023-06-21 09:43 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-bottom: 8px;
может для последнего элемента margin-bottom надо отменять?

2023-06-21 09:43 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                <div class="content__wrapper">
.skeleton__box?

2023-06-24 14:25 UTC, 25S01ve commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 400px;
Переименовал, но без этого враппера два ряда рядом с картинкой не встанут будут ниже либо выстроятся картинка и эти два в ряд

2023-06-24 14:30 UTC, 25S01ve commented on 04-lection2/02-skeleton/skeleton.css
> +    margin: 0 16px 24px 0;
ok

2023-06-24 14:31 UTC, 25S01ve commented on 04-lection2/02-skeleton/skeleton.css
> +.wrapper{
ok

2023-06-24 14:34 UTC, 25S01ve commented on 04-lection2/02-skeleton/skeleton.css
> +.imgName__wrapper{
переименовал

2023-06-24 14:35 UTC, 25S01ve commented on 04-lection2/02-skeleton/skeleton.css
> +    justify-content: flex-start;
ok

2023-06-24 14:42 UTC, 25S01ve commented on 04-lection2/02-skeleton/skeleton.css
> +    padding-top: 8px;
Попробовал, тогда они просто подскакивают кверху а по дизайну у картинки от края паддинг 24 а у контента 32 потому паддинг и нарисовал для бокса

2023-06-24 14:45 UTC, 25S01ve commented on 04-lection2/02-skeleton/skeleton.css
> +    border: 1px solid var(--grey-2);
ok

2023-06-24 14:45 UTC, 25S01ve commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-bottom: 8px;
ok

2023-07-05 21:33 UTC, GSemikozov requested changes

2023-07-05 21:33 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 400px;
лишнее ограничение ширины (не совсем понятно зачем это делаем. Если блок не тянется на всю доступную ширину по родителю - то может flex-grow: 1 или flex-shrink: 0 помогут?)

2023-07-07 08:21 UTC, 25S01ve commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 400px;
Просто сделал width: 100% все сработало

2023-07-09 23:08 UTC, GSemikozov approved these changes

2023-07-09 23:08 UTC, merged