Calendar solution
js-tasks-ru/htmlcss-20230530_prasolovp-s pull request #18
Opened 2023-06-25 01:18 UTC by 25S01ve

2023-06-25 01:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-25 19:25 UTC, GSemikozov requested changes

2023-06-25 19:25 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +	padding: 28px 30px;
все-таки `28 26 32`

2023-06-25 19:25 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +	padding: 8px 11px;
точно тут и ниже без паддингов не обойтись? stretch при выравнивании через родителя не поможет?

2023-06-26 03:35 UTC, 25S01ve commented on 05-lection3/03-calendar/calendar.css
> +	padding: 8px 11px;
Попробовал, в результате циферки оказались наверху квадратиков при выравнивании justify-self:center и align-self: center растягивание потерялось и падинги стали прям возле циферок, эффект был утрачен. Так что лучшего варианта чем поставить паддинги на уровне модификатора мне в голову не пришло.

2023-06-26 03:51 UTC, 25S01ve commented on 05-lection3/03-calendar/calendar.css
> +	padding: 28px 30px;
ок

2023-06-26 04:20 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-28 02:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-30 20:09 UTC, GSemikozov approved these changes

2023-06-30 20:09 UTC, merged