Checkbox solution
js-tasks-ru/htmlcss-20230530_prasolovp-s pull request #23
Opened 2023-07-05 14:39 UTC by 25S01ve

2023-07-05 14:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-07-05 21:28 UTC, GSemikozov requested changes

2023-07-05 21:28 UTC, GSemikozov commented on 07-lection5/01-checkbox/index.html
> +            </div> <br>
в один лейбл заворачиваем один инпут, итого - будет 2 варианта

2023-07-07 07:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-07-07 07:28 UTC, 25S01ve commented on 07-lection5/01-checkbox/index.html
> +            </div> <br>
Сделано

2023-07-07 08:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-07-07 08:21 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-07-09 23:05 UTC, GSemikozov approved these changes

2023-07-09 23:05 UTC, merged